version: '3'
services:

    db:
        image: 'mongo'
        environment:
            - MONGO_INITDB_DATABASE=fizzbuzzdatabase
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=secret
    api:
        build: ./src
        environment:
            - MONGODB_HOST=db
            - MONGODB_PORT=27017
            - MONGODB_USERNAME=admin
            - MONGODB_PASSWORD=secret
        links:
            - db
        depends_on:
            - db
    nginx:
      restart: always
      build: ./nginx/
      ports:
        - "4242:80"
      links:
        - api
      depends_on:
        - db
        - api
